Add docs
esl/cets pull request #47
Opened 2024-01-03 00:11 UTC by arcusfelis

Docs generated with:

```
rebar3 docs
```

in the `doc` directory.

2024-01-12 18:03 UTC, NelsonVides commented on src/cets_long.erl
> +%% User provided function to executre.
```suggestion
%% User provided function to execute.
```

2024-01-12 18:06 UTC, NelsonVides requested changes
One thing is missing: https://github.com/esl/cets/blob/main/src/cets.app.src

Compare for example to https://github.com/esl/amoc/blob/master/src/amoc.app.src

We need to provide there `{vsn, git}`, license and links.

2024-01-12 19:52 UTC, NelsonVides requested changes

2024-01-12 19:52 UTC, NelsonVides commented on rebar.config
> +    ]},
Please remove this

2024-01-12 19:52 UTC, NelsonVides commented on rebar.config
> +    ]},
Why do we need this alias to begin with? Why can't we just do `rebar3 ex_doc` like everyone else do?

2024-01-12 19:52 UTC, NelsonVides commented on rebar.config
> +{plugins, [rebar3_ex_doc, hex]}.
It's called `rebar3_hex`, not `hex`: https://hex.pm/packages/rebar3_hex

2024-01-12 19:52 UTC, NelsonVides commented on src/cets.app.src
> +    {licenses, ["Apache License 2.0"]},
License should be in the accepted formatting, see: https://spdx.org/licenses/
```suggestion
    {licenses, ["Apache-2.0"]},
```

2024-01-12 19:52 UTC, NelsonVides commented on src/cets.app.src
> +    {pkg_name, "cets"},
This is not needed, the default is already the name of the application.

2024-01-15 09:34 UTC, arcusfelis commented on src/cets.app.src
> +    {licenses, ["Apache License 2.0"]},
fullname works too, actually

2024-01-15 10:27 UTC, NelsonVides approved these changes
LGTM 👌🏽

2024-01-15 10:27 UTC, merged